### ISSUE TITLE
CLI fails, ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by edygar** [remix-pwa/remix-pwa#100]
Can't use the cli, it's failing right at its start:

```❯ npx remix-pwa@latest -h
/home/.volta/tools/image/packages/remix-pwa/lib/node_modules/remix-pwa/dist/cli.js:17
const remixConfig = require(path.join(process.cwd(), "remix.config.js")); // remix.config.js file
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/remix.config.js from /home/.volta/tools/image/packages/remix-pwa/lib/node_modules/remix-pwa/dist/cli.js not supported.
Instead change the require of remix.config.js in /home/.volta/tools/image/packages/remix-pwa/lib/node_modules/remix-pwa/dist/cli.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/.volta/tools/image/packages/remix-pwa/lib/node_modules/remix-pwa/dist/cli.js:17:21) {
  code: 'ERR_REQUIRE_ESM'
}
```

Steps to reproduce

```sh
npx create-remix@latest --typescript --install --template epicweb-dev/epic-stack
npx remix-pwa@latest -h
```

**Comment by ShafSpecs** [comment]
Noted. Would review this ASAP

**Comment by ShafSpecs** [comment]
@edygar reason for the error is that `remix-pwa` requires you to run it in a remix application folder. 

It should not require a remix folder for the `--help` command though

**Comment by edygar** [comment]
@ShafSpecs, look again:

```
💿 That's it! `cd` into "/Users/username/dev/personal/test" and check the README for development and deploy instructions!
❯ cd test
❯ npx remix-pwa@latest
/Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:17
const remixConfig = require(path.join(process.cwd(), "remix.config.js")); // remix.config.js file
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/username/dev/personal/test/remix.config.js from /Users/username/.npm/_npx/2a790d8a53532af9/node_modules
/remix-pwa/dist/cli.js not supported.
Instead change the require of remix.config.js in /Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js to a dynamic import() which is availab
le in all CommonJS modules.
    at Object.<anonymous> (/Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:17:21) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.16.0

```

**Comment by ShafSpecs** [comment]
Noted. 

Would look at it right now

**Comment by ShafSpecs** [comment]
<img width="874" alt="image" src="https://github.com/remix-pwa/remix-pwa/assets/69679506/323214a5-8226-462f-9b69-020455e97993">

It worked here. Try to run: `npx remix-pwa@latest -v` and paste the version

**Comment by edygar** [comment]
I'm specifically reporting the bug while using on a remix app with the template `epicweb-dev/epic`. It imports the `remix-flat-routes` maybe that's the problem

```
 ❯ npx remix-pwa@latest -v
/Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:17
const remixConfig = require(path.join(process.cwd(), "remix.config.js")); // remix.config.js file
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/username/dev/personal/test/remix.config.js from /Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js not supported.
Instead change the require of remix.config.js in /Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:17:21) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.16.0
❯ npx remix-pwa@latest -h
/Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:17
const remixConfig = require(path.join(process.cwd(), "remix.config.js")); // remix.config.js file
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/username/dev/personal/test/remix.config.js from /Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js not supported.
Instead change the require of remix.config.js in /Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:17:21) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.16.0
❯ npx remix-pwa@latest
/Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:17
const remixConfig = require(path.join(process.cwd(), "remix.config.js")); // remix.config.js file
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/username/dev/personal/test/remix.config.js from /Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js not supported.
Instead change the require of remix.config.js in /Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/username/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:17:21) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.16.0
```

It doesn't happen on a newly created remix app without any template:


```
💿 That's it! `cd` into "/Users/username/dev/personal/my-remix-app" and check the README for development and deploy instructions!
❯ cd revolut-dev-apps
❯ cd my-remix-app
❯ npx remix-pwa@latest -h

______               _       ______ _    _  ___  
| ___ \             (_)      | ___ \ |  | |/ _ \ 
| |_/ /___ _ __ ___  ___  __ | |_/ / |  | / /_\ \
|    // _ \ '_ ` _ \| \ \/ / |  __/| |/\| |  _  |
| |\ \  __/ | | | | | |>  <  | |   \  /\  / | | |
\_| \_\___|_| |_| |_|_/_/\_\ \_|    \/  \/\_| |_/


Usage:  npx remix-pwa@latest [OPTIONS]```

**Comment by ShafSpecs** [comment]
Oh ok! 👍 

That explains it. I would look at adding support for `remix-flat-routes` then or simply finding another way to do it. Stay tuned!

**Comment by j14y** [comment]
The reason this happens is due to conflicting module resolution systems. Since node currently has two different module systems, CommonJS and ECMAScript, it attempts to use one or the another when loading a module, and this affects the import syntax if you attempt to load an ECMAScript module from a CommonJS module. In this particular case, node treats the `cli.js` file in the CLI distribution as a CommonJS module, and uses its loader (permalink to why this is the case: https://nodejs.org/api/modules.html#enabling). When attempting to fetch the Remix configuration, ECMAScript **may** be used if the `type` field in the package.json of the Remix project is set to `module`. This varies depending on the template or set-up of the project and is not consistent (i.e. some templates set this field like Express, while others such as the Cloudflare Pages configuration do not). In the case where the Remix configuration resolves to an ES module, the error will occur, since the CLI implicitly assumes that it is a CommonJS module.

The quick fix is to just update the `cli.js` file on your file system by hand to import the remix configuration correctly while the issue is resolved:

```
const remixConfig = import(path.join(process.cwd(), "remix.config.js"))

if (remixConfig.default?.future.v2_routeConvention == true) {
    v2_routeConvention = true;
}
```
