### ISSUE TITLE
CLI install fail: Cannot read properties of undefined (reading 'v2_routeConvention')

### ISSUE THREAD

**Issue by vkmagalhaes** [remix-pwa/remix-pwa#101]
Hi there 👋🏻 

I'm trying to install the CLI on an existing Remix project but I'm getting the following error:

```
> npx remix-pwa@latest   
/Users/vinicius/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:18
if (remixConfig?.future.v2_routeConvention == true) {
                       ^

TypeError: Cannot read properties of undefined (reading 'v2_routeConvention')
    at Object.<anonymous> (/Users/vinicius/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:18:24)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

Any idea what could be going on? This is a Remix stack running on Cloudflare Pages, all packages on the latest Remix version `1.17.1`.

**Comment by ShafSpecs** [comment]
@vkmagalhaes Noted. Question, do you have the `future` flag in your Remix config.?

**Comment by vkmagalhaes** [comment]
> @vkmagalhaes Noted. Question, do you have the `future` flag in your Remix config.?

I did not. Simply adding `future: {},` to it fixed the problem, thank you @ShafSpecs 🙇🏻

**Comment by vkmagalhaes** [comment]
Sorry, mistakenly closed the ticket.

**Comment by ShafSpecs** [comment]
@vkmagalhaes alright. Would leave this open till a fix is provided

**Comment by LagunaISW** [comment]
I found this issue today. `npx remix-pwa@latest` on my project a got this error: 
```
if (config.future && config.future.v2_routeConvention == true) {
               ^

TypeError: Cannot read properties of undefined (reading 'future')
    at cli (/.npm/_npx/2a790d8a53532af9/node_modules/remix-pwa/dist/cli.js:285:16)
``` 

This is how my `remix.config.js` looks:
```
/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  cacheDirectory: "./node_modules/.cache/remix",
  future: {
    v2_errorBoundary: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
  ignoredRouteFiles: ["**/.*", "**/*.test.{js,jsx,ts,tsx}"],
  postcss: true,
  tailwind: true,
};
```
@ShafSpecs fyi

**Comment by ShafSpecs** [comment]
@LagunaISW Noted! Would look into it ASAP

**Comment by ShafSpecs** [comment]
@LagunaISW `v2.0.3` should provide a fix for that 👍

**Comment by LagunaISW** [comment]
@ShafSpecs, it is working as expected now. Thanks!
