### ISSUE TITLE
Question: TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by typytypytypy** [remix-pwa/remix-pwa#111]
In production I am seeing this error:
```
TypeError: Cannot read properties of null (reading 'log')
```

It points me to this line in entry.worker.js
```
i.has(O) || (null.log("Caching data for", O),
```

I know logs are not supposed to be on in production, but I'm not sure I'm supposed to be getting this error either. Anything I should look for?

**Comment by ShafSpecs** [comment]
@typytypytypy Thanks for informing us! Would look into this ASAP, yep you are right, logs aren't meant to be in production at all

**Comment by ShafSpecs** [comment]
@typytypytypy Possible fix: https://github.com/remix-pwa/sw/pull/22

To be honest, no idea why that could occur.

**Comment by typytypytypy** [comment]
Thank you! I'll test today and close this if it is resolved

**Comment by typytypytypy** [comment]
I upgraded to 1.1.0 and then my build broke with this error:
```
yarn run v1.22.19
  $ remix-serve build
  /app/build/index.js:50311
  })();
    ^
  ReferenceError: self is not defined
```

**Comment by ShafSpecs** [comment]
> I upgraded to 1.1.0 and then my build broke with this error:
> ```
> yarn run v1.22.19
>   $ remix-serve build
>   /app/build/index.js:50311
>   })();
>     ^
>   ReferenceError: self is not defined
> ```

@typytypytypy 🙆‍♂️ Would look at it soon enough, in the meantime please downgrade the version. I would look at this today, haven't seen this bug before

**Comment by ShafSpecs** [comment]
@typytypytypy Are you running `yarn run start`?

**Comment by convcha** [comment]
Hi, thanks for making a great library!
I am amazed at how easy it is to cache.

https://github.com/convcha/remix-pwa-issue
I had the same problem in my environment and created a repository to reproduce it.

```
node -v
v20.5.0
```

Repro steps:  
1. `git clone https://github.com/convcha/remix-pwa-issue.git`
2. `cd remix-pwa-issue`
3. `npm install`
4. `npm run build`
5. `npm run start`
6. The following error occurs.

```
npm run start

> start
> remix-serve build


/remix-pwa-issue/build/index.js:162
})();
  ^
ReferenceError: self is not defined
    at /remix-pwa-issue/build/index.js:156:3
    at Object.<anonymous> (/remix-pwa-issue/build/index.js:162:3)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/remix-pwa-issue/node_modules/@remix-run/serve/dist/cli.js:34:13)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
```

```
// public/entry.worker.js
self.__DISABLE_PWA_DEBUG_LOGS=!0,self.__DISABLE_PWA_DEV_LOGS=!0,self.__DISABLE_PWA_INFO_LOGS=!0,self.__DISABLE_PWA_WARN_LOGS=!0,self.__DISABLE_PWA_ERROR_LOGS=!0;
```

Is it because the log output process is included in the production build?

https://github.com/convcha/remix-pwa-issue/commits/main
See the commit history for the changes I made to the Remix template.

**Comment by ShafSpecs** [comment]
@convcha Thanks for the repro, on it!

> Hi, thanks for making a great library!
I am amazed at how easy it is to cache.

Glad you are loving it 😄

**Comment by ShafSpecs** [comment]
Thanks for the repro.

I believe it has been fixed, published a patch now and that should fix it

**Comment by ShafSpecs** [comment]
If the issue has been solved, please don't forget to close this issue ✌️!

**Comment by convcha** [comment]
> If the issue has been solved, please don't forget to close this issue ✌️! 

It was fixed!!!
Thanks :)
