### ISSUE TITLE
Fonts and svg error in remix-pwa dev

### ISSUE THREAD

**Issue by arpitdalal** [remix-pwa/remix-pwa#128]
I've a styles/font.css in app dir and that imports a bunch of woff and woff2 files from the `public` dir. And I'm using svg sprites and that is also throwing an error on `remix-pwa dev`. What could fix these?

fonts error:
```sh
✘ [ERROR] Could not resolve "/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-200.woff2"

    app/styles/font.css:8:6:
      8 │     url('/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-200.woff2')
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

svg error:
```sh
✘ [ERROR] No loader is configured for ".svg" files: app/components/ui/icons/sprite.svg

    app/components/ui/icon.tsx:4:17:
      4 │ import href from './icons/sprite.svg'
        ╵                  ~~~~~~~~~~~~~~~~~~~~
```

**Comment by ShafSpecs** [comment]
Does it throw an error if you run without `remix-pwa dev` @arpitdalal?

**Comment by arpitdalal** [comment]
Nope, I've been using this project for a long time, it's deployed in prod as well. I just did remix-pwa init today and dev is broken

**Comment by ShafSpecs** [comment]
> Nope, I've been using this project for a long time, it's deployed in prod as well. I just did remix-pwa init today and dev is broken

Can you please attempt to remove it and re-try? These don't look like `remix-pwa` errors. They usually have a 404 format

**Comment by arpitdalal** [comment]
removed all changes done by `remix-pwa` and uninstalled all deps and then ran `npm run dev`, the output:
```sh
─ npm run dev                                                                                               ─╯

> predev
> npm run build:icons --silent

Generated 49 icons

> dev
> remix dev -c "node ./server/dev-server.js" --manual


 💿  remix dev

 info  building...
 info  built (4.7s)
10:06:26 AM [tsx] rerunning
Debugger listening on ws://127.0.0.1:9229/8bab0d00-59f2-47f7-a866-a7b4719ac5c5
For help, see: https://nodejs.org/en/docs/inspector
🔶 Mock server installed
🚀  We have liftoff!
Local:            http://localhost:3000
On Your Network:  http://10.0.0.17:3000
Press Ctrl+C to stop
```

**Comment by arpitdalal** [comment]
added remix-pwa back in a different branch to test things out. Here's the whole error. (I've removed some repeating errors for fonts as I've a lot of them)
```console
╰─ npm run dev                                                                                                                                                    ─╯

> predev
> npm run build:icons --silent

Generated 49 icons

> dev
> run-p dev:*


> dev:worker
> remix-pwa dev


> dev:remix
> remix dev -c "node ./server/dev-server.js" --manual


 💿  remix dev

 info  building...
🏗️ Building Service Worker in development mode...

💿 Built Service Worker in: 45.011ms
👀 Watching for changes in the service worker file...
✘ [ERROR] No loader is configured for ".svg" files: app/components/ui/icons/sprite.svg

    app/components/ui/icon.tsx:4:17:
      4 │ import href from './icons/sprite.svg'
        ╵                  ~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "crypto"

    node_modules/@epic-web/totp/index.js:4:24:
      4 │ import * as crypto from 'crypto'
        ╵                         ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-200.woff2"

    app/styles/font.css:8:6:
      8 │     url('/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-200.woff2')
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-200.woff"

    app/styles/font.css:11:7:
      11 │       url('/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-200.woff')
         ╵           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[---------------------------------]
MORE SIMILAR ERRORS FOR FONTS
[---------------------------------]

/node_modules/esbuild/lib/main.js:1650
  let error = new Error(text);
              ^

Error: Build failed with 30 errors:
app/components/ui/icon.tsx:4:17: ERROR: No loader is configured for ".svg" files: app/components/ui/icons/sprite.svg
app/styles/font.css:8:6: ERROR: Could not resolve "/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-200.woff2"
app/styles/font.css:11:7: ERROR: Could not resolve "/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-200.woff"
app/styles/font.css:21:6: ERROR: Could not resolve "/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-200italic.woff2"
app/styles/font.css:24:7: ERROR: Could not resolve "/fonts/nunito-sans/nunito-sans-v12-latin_latin-ext-200italic.woff"
...
    at failureErrorWithLog (/node_modules/esbuild/lib/main.js:1650:15)
    at /node_modules/esbuild/lib/main.js:1059:25
    at runOnEndCallbacks (/node_modules/esbuild/lib/main.js:1485:45)
    at buildResponseToResult (/node_modules/esbuild/lib/main.js:1057:7)
    at /node_modules/esbuild/lib/main.js:1069:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/node_modules/esbuild/lib/main.js:1068:54)
    at handleRequest (/node_modules/esbuild/lib/main.js:731:17)
    at handleIncomingPacket (/node_modules/esbuild/lib/main.js:756:7)
    at Socket.readFromStdout (/node_modules/esbuild/lib/main.js:679:7) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v18.17.1
The service was stopped: write EPIPE
ERROR: "dev:worker" exited with 1.
```

**Comment by ShafSpecs** [comment]
Super weird @arpitdalal. Would throw this open and assign it a high priority. Can't even tell if this is a compiler thing or service worker or runtime issue (shouldn't be any). Would keep an eye on this one

**Comment by arpitdalal** [comment]
This codebase is based on [epic-stack](https://github.com/epicweb-dev/epic-stack). I'll create a minimal reproducible example soon as I cannot share my code as it's enterprise.

**Comment by ShafSpecs** [comment]
> This codebase is based on [epic-stack](https://github.com/epicweb-dev/epic-stack). I'll create a minimal reproducible example soon as I cannot share my code as it's enterprise.

No problem. Completely understandable. I am just wondering how the compiler went that far. Would be digging much further, no worries

**Comment by arpitdalal** [comment]
Here's the minimum reproducible example. There are 2 branches, `main` is without remix-pwa and `remix-pwa` is with. Here's the command and output of `remix-pwa init` on that branch
```console
╰─ npx remix-pwa@latest init                                                                                              ─╯
✔ Is this a TypeScript or JavaScript project? Pick the opposite for chaos! · ts
✔ Do you want to integrate workbox into your project? (y/N) · false
✔ Do you want to utilise precaching in this project? (y/N) · false
✔ What features of remix-pwa do you need? Don't be afraid to pick all! · sw, manifest, push, utils, icons
✔ What package manager do you use? · npm
✔ Do you want to run npm install? (Y/n) · true
⠋ Integrating Service Worker...
⠋ Integrating Web Manifest...
✔ Successfully integrated Service Worker!
✔ Successfully ran npm install!


✔ Successfully ran postinstall scripts!
```
On this branch, the first commit `remix-pwa init` is after running this init command and the second commit `modify remix-pwa` is me modifying files like package.json to modify the `dev` script to what it was before and following the [installation guide](https://remix-pwa.run/docs/installation) from the remix-pwa website.

Surprisingly, the font errors aren't here, but the crypto and SVG errors are still here
```console
👀 Watching for changes in the service worker file...
✘ [ERROR] No loader is configured for ".svg" files: app/components/ui/icons/sprite.svg

    app/components/ui/icon.tsx:4:17:
      4 │ import href from './icons/sprite.svg'
        ╵                  ~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "crypto"

    node_modules/@epic-web/totp/index.js:4:24:
      4 │ import * as crypto from 'crypto'
        ╵                         ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

**Comment by arpitdalal** [comment]
Was able to remove the crypto error too by exporting everything from `@epic-web/totp` from a `server.ts` file so it's not bundled in the client code. [Commit](https://github.com/arpitdalal/mre-remix-pwa/commit/803af865cb9340ea7e8e55f66beb1047aa0e6949)

**Comment by ShafSpecs** [comment]
> Was able to remove the crypto error too by exporting everything from `@epic-web/totp` from a `server.ts` file so it's not bundled in the client code. [Commit](https://github.com/arpitdalal/mre-remix-pwa/commit/803af865cb9340ea7e8e55f66beb1047aa0e6949)

The new remix pwa coming out soon would attempt to fix the issue of server/client code getting into worker bundle. 👍

**Comment by ShafSpecs** [comment]
*This issue has been resolved, if you have any further questions, please open a new issue*

**Comment by arpitdalal** [comment]
@ShafSpecs 
Where is the new version? How do I install it?

**Comment by ShafSpecs** [comment]
> @ShafSpecs Where is the new version? How do I install it?

@arpitdalal Sorry for the delay. I couldn't release the version until yesterday. You can install the latest version of remix-pwa and `dev` to get the new changes
