### ISSUE TITLE
Error when using appDirectory

### ISSUE THREAD

**Issue by Dalez** [remix-pwa/remix-pwa#145]
I have Remix set up to use appDirectory:

`remix({ appDirectory: "./src/app" })`

But when I add `remixPWA()` to my plugins list and try to start the dev server, I get:

```
$ remix vite:dev
Error: Missing "root" route file in /Users/.../app
    at resolveConfig (/Users/.../node_modules/@remix-run/dev/dist/config.js:154:11)
    at async resolveOptions (file:///Users/.../node_modules/@remix-pwa/dev/dist/src/resolver.js:28:50)
    at async configResolved (file:///Users/.../node_modules/@remix-pwa/dev/dist/src/plugins/main.js:13:27)
    at async Promise.all (index 1)
    at async resolveConfig (file:///Users/.../node_modules/vite/dist/node/chunks/dep-BBHrJRja.js:68239:5)
    at async _createServer (file:///Users/...node_modules/vite/dist/node/chunks/dep-BBHrJRja.js:64490:20)
    at async dev (/Users/.../node_modules/@remix-run/dev/dist/vite/dev.js:39:16)
    at async Object.viteDev (/Users/.../node_modules/@remix-run/dev/dist/cli/commands.js:220:3)
    at async Object.run (/Users/.../node_modules/@remix-run/dev/dist/cli/run.js:271:7)
error Command failed with exit code 1.
```

Is there a setting I'm missing? Thanks!

**Comment by ShafSpecs** [comment]
> I have Remix set up to use appDirectory:
> 
> `remix({ appDirectory: "./src/app" })`
> 
> But when I add `remixPWA()` to my plugins list and try to start the dev server, I get:
> 
> ```
> $ remix vite:dev
> Error: Missing "root" route file in /Users/.../app
>     at resolveConfig (/Users/.../node_modules/@remix-run/dev/dist/config.js:154:11)
>     at async resolveOptions (file:///Users/.../node_modules/@remix-pwa/dev/dist/src/resolver.js:28:50)
>     at async configResolved (file:///Users/.../node_modules/@remix-pwa/dev/dist/src/plugins/main.js:13:27)
>     at async Promise.all (index 1)
>     at async resolveConfig (file:///Users/.../node_modules/vite/dist/node/chunks/dep-BBHrJRja.js:68239:5)
>     at async _createServer (file:///Users/...node_modules/vite/dist/node/chunks/dep-BBHrJRja.js:64490:20)
>     at async dev (/Users/.../node_modules/@remix-run/dev/dist/vite/dev.js:39:16)
>     at async Object.viteDev (/Users/.../node_modules/@remix-run/dev/dist/cli/commands.js:220:3)
>     at async Object.run (/Users/.../node_modules/@remix-run/dev/dist/cli/run.js:271:7)
> error Command failed with exit code 1.
> ```
> 
> Is there a setting I'm missing? Thanks!

No, it should work. The error seems to come from this function: https://github.com/remix-pwa/monorepo/blob/d55d9f1b4e6c7a8b94e11d15ef2788726e93efb6/packages/dev/src/resolver.ts#L25

It's probably with regards to how remix handles the app directory. If it won't break your app, the current temporary fix would be to just use default. And I would look at rolling out a fix soon 👍

**Comment by ShafSpecs** [comment]
Fix should be out now. Sorry about not dropping an update when it dropped

**Comment by Dalez** [comment]
Brilliant, thank you! All seems to be working :)
