### ISSUE TITLE
BUILD: [vite-plugin-remix-pwa:virtual-entry-sw] Could not load virtual:entry-sw 

### ISSUE THREAD

**Issue by Magzter** [remix-pwa/remix-pwa#147]
Hey guys, running a relatively new remix project and have been struggling with this error for the last few days.

This is after following the basic instructions at: https://remix-pwa.run/docs/main/quick-start

It seems to fail to build the worker file but I haven't been able to make sense of this error, I've tried multiple machines (ubuntu/Mac) and node versions (node 18/20) but it consistently produces this.

I've tried following the runtimes guideline to do my own runtime instead but produces the same error.

<img width="1440" alt="Screenshot 2024-05-01 at 5 05 36 PM" src="https://github.com/remix-pwa/remix-pwa/assets/1981253/7deec6ca-4c8d-4c3a-9f54-3512d68f6dde">

Package.json

```{
  "name": "my-remix-app",
  "private": true,
  "sideEffects": false,
  "type": "module",
  "scripts": {
    "build": "remix vite:build",
    "dev": "sst bind remix vite:dev",
    "lint": "eslint --ignore-path .gitignore --cache --cache-location ./node_modules/.cache/eslint .",
    "start": "remix-serve ./build/server/index.js",
    "typecheck": "tsc"
  },
  "dependencies": {
    "@nextui-org/autocomplete": "^2.0.16",
    "@nextui-org/dropdown": "^2.1.18",
    "@nextui-org/react": "^2.3.1",
    "@nextui-org/use-infinite-scroll": "^2.1.3",
    "@react-stately/data": "^3.11.2",
    "@remix-pwa/sw": "^3.0.3",
    "@remix-pwa/worker-runtime": "^2.1.1",
    "@remix-run/node": "^2.9.0",
    "@remix-run/react": "^2.9.0",
    "@remix-run/serve": "^2.9.0",
    "framer-motion": "^11.1.1",
    "i": "^0.3.7",
    "isbot": "^4.1.0",
    "lodash": "^4.17.21",
    "lodash.debounce": "^4.0.8",
    "next-themes": "^0.3.0",
    "npm": "^10.5.2",
    "react": "^18.3.0-canary-593ecee66-20231114",
    "react-animated-numbers": "^0.18.0",
    "react-dom": "^18.3.0-canary-593ecee66-20231114",
    "remix-auth": "^3.6.0",
    "remix-auth-form": "^1.4.0",
    "remix-auth-google": "^2.0.0"
  },
  "devDependencies": {
    "@remix-pwa/dev": "^3.0.5",
    "@remix-run/dev": "^2.8.1",
    "@types/react": "^18.2.20",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.7.4",
    "@typescript-eslint/parser": "^6.7.4",
    "autoprefixer": "^10.4.19",
    "eslint": "^8.38.0",
    "eslint-import-resolver-typescript": "^3.6.1",
    "eslint-plugin-import": "^2.28.1",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.3",
    "typescript": "^5.1.6",
    "vite": "^5.1.0",
    "vite-tsconfig-paths": "^4.2.1"
  },
  "overrides": {
    "react": "^18.3.0-canary-593ecee66-20231114",
    "react-dom": "^18.3.0-canary-593ecee66-20231114"
  },
  "engines": {
    "node": ">=18.0.0"
  }
}
```

**Comment by ShafSpecs** [comment]
Hello @Magzter, does this occur on build? I think I've spotted the error, remix pwa is attempting to build before remix has finished building. Is your remix pwa plugin after remix plugin in your Vite config?

**Comment by Magzter** [comment]
Hey @ShafSpecs , it is after, below is a copy of the vite configuration.

```
import { vitePlugin as remix } from "@remix-run/dev";
import { installGlobals } from "@remix-run/node";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths"
import { remixPWA } from '@remix-pwa/dev'

installGlobals();

export default defineConfig({
  plugins: [
    remix(
      // { ssr: false }
    ),
    remixPWA({
      //workerMinify: true,
      //workerEntryPoint: './runtime.js'
    }),
    tsconfigPaths()
  ],
});

```

**Comment by ShafSpecs** [comment]
> Hey @ShafSpecs , it is after, below is a copy of the vite configuration.
> 
> ```
> import { vitePlugin as remix } from "@remix-run/dev";
> import { installGlobals } from "@remix-run/node";
> import { defineConfig } from "vite";
> import tsconfigPaths from "vite-tsconfig-paths"
> import { remixPWA } from '@remix-pwa/dev'
> 
> installGlobals();
> 
> export default defineConfig({
>   plugins: [
>     remix(
>       // { ssr: false }
>     ),
>     remixPWA({
>       //workerMinify: true,
>       //workerEntryPoint: './runtime.js'
>     }),
>     tsconfigPaths()
>   ],
> });
> 
> ```

The error only throws on build, right? I would have to check that out. Seems like a bug, do you have a reproduction?

**Comment by Magzter** [comment]
On both dev and prod builds, I've got around it at the moment by manually putting an entry.worker.js file in public to continue playing with other SPA features.

I've just jumped into bed but will work on getting you an easily cloned reproduced project tomorrow.

**Comment by Magzter** [comment]
@ShafSpecs I managed to figure it out as I was deleting stuff in the reproduce project but it looks like it fails at some sort of duplicate import lint/vite rule? However my normal Vite build doesn't throw any errors with the pwa plugin removed.

https://github.com/Magzter/remix-pwa-build-bug

If you uncomment one of the imports at my-remix-app/app/routes/_index.tsx:7 and run build you will reproduce the error.

Maybe whatever vite build error happens needs to be passed through to the CLI?

**Comment by ShafSpecs** [comment]
> @ShafSpecs I managed to figure it out as I was deleting stuff in the reproduce project but it looks like it fails at some sort of duplicate import lint/vite rule? However my normal Vite build doesn't throw any errors with the pwa plugin removed.
> 
> https://github.com/Magzter/remix-pwa-build-bug
> 
> If you uncomment one of the imports at my-remix-app/app/routes/_index.tsx:7 and run build you will reproduce the error.
> 
> Maybe whatever vite build error happens needs to be passed through to the CLI?

Thanks, it's 2am here so won't be able to check it out for a few hours 😄.

**Comment by ShafSpecs** [comment]
Looking at the file, you seem to have imported them before. If I uncomment, you would end up importing twice

**Comment by Magzter** [comment]
> Looking at the file, you seem to have imported them before. If I uncomment, you would end up importing twice

Yes but it doesn't throw an error on my build with the PWA plugin removed and the error thrown by PWA plugin is not clear as to what the build error is. I don't mind the error as it's given me a chance to clean it up but I wouldn't have found it had I not created a new project and removed stuff xD

You can see that by uncommenting the double import and commenting out the pwa plugin then running build. I haven't done anything to configure build rules just using remix out of the box.

**Comment by purplecandy** [comment]
Hey @ShafSpecs , what are you talking about? I just ran into the issue when deploying the cloudflare pages. 

Here's the error and the pwa is built first

```
> remix-pwa build
00:53:41.101	
00:53:41.593	🏗️ Building Service Worker in production mode...
00:53:41.593	
00:53:41.601	✘ [ERROR] Could not resolve "virtual:entry-sw"
00:53:41.601	
00:53:41.601	    ../../node_modules/.pnpm/@remix-pwa+worker-runtime@2.1.2_@remix-run+server-runtime@2.10.3/node_modules/@remix-pwa/worker-runtime/dist/src/service-worker.internal.js:3:23:
00:53:41.602	      3 │ import * as build from 'virtual:entry-sw';
00:53:41.602	        ╵                        ~~~~~~~~~~~~~~~~~~
00:53:41.602	
00:53:41.602	  You can mark the path "virtual:entry-sw" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
00:53:41.603	
00:53:41.619	Error: Build failed with 1 error:
00:53:41.619	../../node_modules/.pnpm/@remix-pwa+worker-runtime@2.1.2_@remix-run+server-runtime@2.10.3/node_modules/@remix-pwa/worker-runtime/dist/src/service-worker.internal.js:3:23: ERROR: Could not resolve "virtual:entry-sw"
00:53:41.619	    at failureErrorWithLog (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1651:15)
00:53:41.619	    at /opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1059:25
00:53:41.619	    at runOnEndCallbacks (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1486:45)
00:53:41.620	    at buildResponseToResult (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1057:7)
00:53:41.620	    at /opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1069:9
00:53:41.620	    at new Promise (<anonymous>)
00:53:41.620	    at requestCallbacks.on-end (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1068:54)
00:53:41.620	    at handleRequest (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:732:17)
00:53:41.620	    at handleIncomingPacket (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:757:7)
00:53:41.620	    at Socket.readFromStdout (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:680:7)
00:53:41.620	    at Socket.emit (node:events:527:28)
00:53:41.620	    at addChunk (node:internal/streams/readable:324:12)
00:53:41.621	    at readableAddChunk (node:internal/streams/readable:297:9)
00:53:41.621	    at Readable.push (node:internal/streams/readable:234:10)
00:53:41.621	    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
00:53:41.621	  errors: [Getter/Setter],
00:53:41.621	  warnings: [Getter/Setter]
00:53:41.621	}
```

**Comment by ShafSpecs** [comment]
> Hey @ShafSpecs , what are you talking about? I just ran into the issue when deploying the cloudflare pages. 
> 
> Here's the error and the pwa is built first
> 
> ```
> > remix-pwa build
> 00:53:41.101	
> 00:53:41.593	🏗️ Building Service Worker in production mode...
> 00:53:41.593	
> 00:53:41.601	✘ [ERROR] Could not resolve "virtual:entry-sw"
> 00:53:41.601	
> 00:53:41.601	    ../../node_modules/.pnpm/@remix-pwa+worker-runtime@2.1.2_@remix-run+server-runtime@2.10.3/node_modules/@remix-pwa/worker-runtime/dist/src/service-worker.internal.js:3:23:
> 00:53:41.602	      3 │ import * as build from 'virtual:entry-sw';
> 00:53:41.602	        ╵                        ~~~~~~~~~~~~~~~~~~
> 00:53:41.602	
> 00:53:41.602	  You can mark the path "virtual:entry-sw" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
> 00:53:41.603	
> 00:53:41.619	Error: Build failed with 1 error:
> 00:53:41.619	../../node_modules/.pnpm/@remix-pwa+worker-runtime@2.1.2_@remix-run+server-runtime@2.10.3/node_modules/@remix-pwa/worker-runtime/dist/src/service-worker.internal.js:3:23: ERROR: Could not resolve "virtual:entry-sw"
> 00:53:41.619	    at failureErrorWithLog (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1651:15)
> 00:53:41.619	    at /opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1059:25
> 00:53:41.619	    at runOnEndCallbacks (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1486:45)
> 00:53:41.620	    at buildResponseToResult (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1057:7)
> 00:53:41.620	    at /opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1069:9
> 00:53:41.620	    at new Promise (<anonymous>)
> 00:53:41.620	    at requestCallbacks.on-end (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:1068:54)
> 00:53:41.620	    at handleRequest (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:732:17)
> 00:53:41.620	    at handleIncomingPacket (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:757:7)
> 00:53:41.620	    at Socket.readFromStdout (/opt/buildhome/repo/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main.js:680:7)
> 00:53:41.620	    at Socket.emit (node:events:527:28)
> 00:53:41.620	    at addChunk (node:internal/streams/readable:324:12)
> 00:53:41.621	    at readableAddChunk (node:internal/streams/readable:297:9)
> 00:53:41.621	    at Readable.push (node:internal/streams/readable:234:10)
> 00:53:41.621	    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
> 00:53:41.621	  errors: [Getter/Setter],
> 00:53:41.621	  warnings: [Getter/Setter]
> 00:53:41.621	}
> ```

Does it say the same thing when you attempt to run npm run build locally?

**Comment by purplecandy** [comment]
No I'm able to build locally without any errors. Now I'm not sure why it's failing when building on cloud flare 😔

**Comment by ShafSpecs** [comment]
> No I'm able to build locally without any errors. Now I'm not sure why it's failing when building on cloud flare 😔

Maybe an environment issue? I haven't had time to work on remix pwa in recent times but would try and keep it up to date 👍

**Comment by micksabox** [comment]
Popping in to say this is happening with me as well. I can't build locally or within GH action. The build fails with:

```
Error during worker build: [vite-plugin-remix-pwa:virtual-entry-sw] Could not load virtual:entry-sw (imported by node_modules/@remix-pwa/worker-runtime/dist/src/service-worker.internal.js): Unexpected token (1:0)
```
There is a difference in the unexpected token compared to the above `Unexpected token (1:0)`

```
"@remix-pwa/dev": "^3.1.0",
"@remix-pwa/sw": "^3.0.9",
"@remix-pwa/worker-runtime": "^2.1.4",
"vite": "^5.4.3",
```

**Comment by ShafSpecs** [comment]
> Popping in to say this is happening with me as well. I can't build locally or within GH action. The build fails with:
> 
> ```
> Error during worker build: [vite-plugin-remix-pwa:virtual-entry-sw] Could not load virtual:entry-sw (imported by node_modules/@remix-pwa/worker-runtime/dist/src/service-worker.internal.js): Unexpected token (1:0)
> ```
> There is a difference in the unexpected token compared to the above `Unexpected token (1:0)`
> 
> ```
> "@remix-pwa/dev": "^3.1.0",
> "@remix-pwa/sw": "^3.0.9",
> "@remix-pwa/worker-runtime": "^2.1.4",
> "vite": "^5.4.3",
> ```

This is quite the bug 😪. I can't replicate it and it happens randomly, my guess is that it is caused by Vite. I would re-evaluate this from the build end and try to get a solution for this 👍
