### ISSUE TITLE
Crashes in docker dev container

### ISSUE THREAD

**Issue by Stephan-MDD** [remix-pwa/remix-pwa#151]
Hi - Im  creating a monorepo with multiple services including a Remix PWA. I use docker to handle all the services in development and it works with Remix but crashes when I add your library. 
It looks like the issue happens here `TypeError: [vite-plugin-remix-pwa:virtual-entry-sw] Could not load virtual:entry-sw`

Let me know if you need more info from me - and thanks in advanced :D

**General info**
- **System** MacOS 14.5 Sonoma (Docker `oven/bun:1.1.3`)
- **Runner** Bun 1.1.20
- **Created wIth** `bunx create-remix@latest` (Today)

> I tried with `npm` too but got the same issue :)

**Command**
```bash
docker-compose up start webapp
```

**Error Message**
```
 ✔ Container webapp  Created                                                                                                                   0.0s 
Attaching to webapp
webapp  | $ remix vite:dev --host 0.0.0.0
webapp  | 🏗️  Building Service Worker in development mode...
webapp  | x Build failed in 44ms
webapp  | Error during worker build: 4 |         hasLoader: false,
webapp  | 5 |         hasAction: false,
webapp  | 6 |         hasWorkerLoader: false,
webapp  | 7 |         hasWorkerAction: false,
webapp  | 8 |     };
webapp  | 9 |     traverse(ast, {
webapp  |            ^
webapp  | TypeError: [vite-plugin-remix-pwa:virtual-entry-sw] Could not load virtual:entry-sw (imported by node_modules/@remix-pwa/worker-runtime/dist/src/service-worker.internal.js): traverse is not a function. (In 'traverse(ast, {
webapp  |     FunctionDeclaration(path) {
webapp  |       const functionName = path.node.id?.name;
webapp  |       if (functionName === "loader")
webapp  |         routeModules.hasLoader = !0;
webapp  |       if (functionName === "action")
webapp  |         routeModules.hasAction = !0;
webapp  |       if (functionName === "workerLoader")
webapp  |         routeModules.hasWorkerLoader = !0;
webapp  |       if (functionName === "workerAction")
webapp  |         routeModules.hasWorkerAction = !0;
webapp  |     },
webapp  |     ArrowFunctionExpression(path) {
webapp  |       if (t.isVariableDeclarator(path.parent) && t.isIdentifier(path.parent.id)) {
webapp  |         const functionName = path.parent.id.name;
webapp  |         if (functionName === "loader")
webapp  |           routeModules.hasLoader = !0;
webapp  |         if (functionName === "action")
webapp  |           routeModules.hasAction = !0;
webapp  |         if (functionName === "workerLoader")
webapp  |           routeModules.hasWorkerLoader = !0;
webapp  |         if (functionName === "workerAction")
webapp  |           routeModules.hasWorkerAction = !0;
webapp  |       }
webapp  |     }
webapp  |   })', 'traverse' is undefined)
webapp  |  code: "PLUGIN_ERROR"
webapp  | 
webapp  |       at resolveRouteModules (/webapp/node_modules/@remix-pwa/dev/dist/src/resolve-route-modules.js:9:8)
webapp  |       at /webapp/node_modules/@remix-pwa/dev/dist/src/plugins/virtual-sw.js:63:76
webapp  | 
webapp  | 2 | import { readFileSync } from 'fs';
webapp  | 3 | import { join } from 'pathe';
webapp  | 4 | export const getWorkerHash = ({ workerBuildDirectory, workerName }) => {
webapp  | 5 |     const hash = createHash('md5');
webapp  | 6 |     const workerPath = join(workerBuildDirectory, `${workerName}.js`);
webapp  | 7 |     hash.update(readFileSync(workerPath, { encoding: 'utf-8' }));
webapp  |                     ^
webapp  | ENOENT: No such file or directory
webapp  |    errno: -2
webapp  |  syscall: "open"
webapp  |    path: "/webapp/public/entry.worker.js"
webapp  | 
webapp  |       at getWorkerHash (/webapp/node_modules/@remix-pwa/dev/dist/src/hash.js:7:17)
webapp  |       at /webapp/node_modules/@remix-pwa/dev/dist/src/plugins/bundler.js:133:24
webapp  | 
webapp  | error: script "dev" exited with code 1
```

## Project Infomations

**Project Structure**
```bash
# root
package.json
compose.yml
webapp/... (remix pwa)
...
```

**webapp/package.json**
```json
{
  "name": "webapp",
  "private": true,
  "sideEffects": false,
  "type": "module",
  "scripts": {
    "build": "remix vite:build",
    "dev": "remix vite:dev",
    "lint": "eslint --ignore-path .gitignore --cache --cache-location ./node_modules/.cache/eslint .",
    "start": "remix-serve ./build/server/index.js",
    "typecheck": "tsc"
  },
  "dependencies": {
    "@remix-pwa/worker-runtime": "^2.1.3",
    "@remix-run/node": "^2.10.3",
    "@remix-run/react": "^2.10.3",
    "@remix-run/serve": "^2.10.3",
    "isbot": "^4.1.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@remix-pwa/dev": "^3.0.7",
    "@remix-run/dev": "^2.10.3",
    "@types/react": "^18.2.20",
    "@types/react-dom": "^18.2.7",
    "@typescript-eslint/eslint-plugin": "^6.7.4",
    "@typescript-eslint/parser": "^6.7.4",
    "autoprefixer": "^10.4.19",
    "eslint": "^8.38.0",
    "eslint-import-resolver-typescript": "^3.6.1",
    "eslint-plugin-import": "^2.28.1",
    "eslint-plugin-jsx-a11y": "^6.7.1",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.4",
    "typescript": "^5.1.6",
    "vite": "^5.1.0",
    "vite-tsconfig-paths": "^4.2.1"
  },
  "engines": {
    "node": ">=20.0.0"
  }
}
```

**webapp/vite.config.ts**
```ts
import { vitePlugin as remix } from '@remix-run/dev';
import { defineConfig } from 'vite';
import tsconfigPaths from 'vite-tsconfig-paths';
import { remixPWA } from '@remix-pwa/dev';

export default defineConfig({
  server: {
    port: process.env.PORT as number | undefined,
  },

  plugins: [
    remix({
      future: {
        v3_fetcherPersist: true,
        v3_relativeSplatPath: true, 
        v3_throwAbortReason: true,
      },
    }),
    tsconfigPaths(),
    remixPWA(),
  ],
});
```

**webapp/Dockerfile**
```dockerfile
FROM oven/bun:1.1.3
WORKDIR /webapp

COPY package.json .
COPY bun.lockb .

COPY . .

RUN bun install --frozen-lockfile

CMD ["bun", "run", "dev", "--", "--host", "0.0.0.0"]
```

**compose.yml**
```yml
services:
  webapp:
    container_name: webapp
    build: ./webapp
    environment:
      PORT: 5175
    ports:
     - 5175:5175
    volumes:
      - /webapp/node_modules
      - ./webapp:/webapp
```

**Comment by ShafSpecs** [comment]
Seems like a babel/ESM import resolution error 🤔. What's  your node version? This seems weird

**Comment by Stephan-MDD** [comment]
@ShafSpecs My node version is `v20.9.0` :) Would you like me to make a repo with a minimal example?

**Comment by ShafSpecs** [comment]
> @ShafSpecs My node version is `v20.9.0` :) Would you like me to make a repo with a minimal example?

Yes please.

**Comment by Stephan-MDD** [comment]
Im using Bun but tried with Node and got a similar error - what runtime will you prefer? :)

**Comment by ShafSpecs** [comment]
> Im using Bun but tried with Node and got a similar error - what runtime will you prefer? :)

I don't have bun on my windows machine, I would prefer Node thanks.

**Comment by Stephan-MDD** [comment]
Here is my  [repository](https://github.com/Stephan-MDD/remix-pwa-bug) my friend :)

**Comment by ShafSpecs** [comment]
![image](https://github.com/user-attachments/assets/930ab591-1f88-473d-bc73-90d2159ee672)

This is my first run. Really weird behaviour on your end, I would like to debug it, I am using Node v22 but I recently upgraded and it was designed to work across Node 10 to 22

**Comment by ShafSpecs** [comment]
The `traverse` error is due to the CJS-ESM interop like I mentioned: https://github.com/babel/babel/issues/13855#issuecomment-945123514

Taken care of in [this file](https://github.com/remix-pwa/monorepo/blob/main/packages/dev/src/babel.ts). Weird it still appears on your PC

**Comment by Stephan-MDD** [comment]
I have a MacBook M1 - could it be related to that?

**Comment by Stephan-MDD** [comment]
If there is anything I can do to help your welcome to ask me :)

**Comment by Stephan-MDD** [comment]
The console error running the container with node looks like this:

``` ✔ Container webapp  Created                                              0.0s 
Attaching to webapp
webapp  | 
webapp  | > dev
webapp  | > remix vite:dev --host 0.0.0.0
webapp  | 
webapp  | failed to load config from /webapp/vite.config.ts
webapp  | Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@remix-pwa/dev' imported from /webapp/vite.config.ts.timestamp-1722166454203-402425dcb8915.mjs
webapp  |     at packageResolve (node:internal/modules/esm/resolve:854:9)
webapp  |     at moduleResolve (node:internal/modules/esm/resolve:927:18)
webapp  |     at defaultResolve (node:internal/modules/esm/resolve:1169:11)
webapp  |     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
webapp  |     at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
webapp  |     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)
webapp  |     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
webapp  |     at link (node:internal/modules/esm/module_job:86:36) {
webapp  |   code: 'ERR_MODULE_NOT_FOUND'
webapp  | }
webapp exited with code 1
```

**Comment by ShafSpecs** [comment]
> I have a MacBook M1 - could it be related to that?

No, no. Not at all.

**Comment by ShafSpecs** [comment]
> The console error running the container with node looks like this:
> 
> ``` ✔ Container webapp  Created                                              0.0s 
> Attaching to webapp
> webapp  | 
> webapp  | > dev
> webapp  | > remix vite:dev --host 0.0.0.0
> webapp  | 
> webapp  | failed to load config from /webapp/vite.config.ts
> webapp  | Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@remix-pwa/dev' imported from /webapp/vite.config.ts.timestamp-1722166454203-402425dcb8915.mjs
> webapp  |     at packageResolve (node:internal/modules/esm/resolve:854:9)
> webapp  |     at moduleResolve (node:internal/modules/esm/resolve:927:18)
> webapp  |     at defaultResolve (node:internal/modules/esm/resolve:1169:11)
> webapp  |     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
> webapp  |     at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
> webapp  |     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:227:38)
> webapp  |     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
> webapp  |     at link (node:internal/modules/esm/module_job:86:36) {
> webapp  |   code: 'ERR_MODULE_NOT_FOUND'
> webapp  | }
> webapp exited with code 1
> ```

Now it seems to be an issue with even locating the dev package 🤔

**Comment by Stephan-MDD** [comment]
I see - maybe the traverse issue has something to do with Bun. Im not locked in any runtime so if Node is what you prefer I'm just using it too 😊

**Comment by Stephan-MDD** [comment]
Any news my friend? :)

**Comment by ShafSpecs** [comment]
Sorry, no. Not atm.
@rphlmr could you please help me try to reproduce this? I'm not sure what could be the issue.

**Comment by rphlmr** [comment]
Hey 👋
Mac M1 too, successful on the first try.

![CleanShot 2024-08-02 at 19 02 41@2x](https://github.com/user-attachments/assets/e8bf68da-2a53-4302-907a-2f306c92dc2c)

It seems you have some `vite.config.ts.timestamp-1722166454203-402425dcb8915.mjs` in your project?
This is a known issue https://github.com/vitejs/vite/issues/13267

Can you delete these files and retry?

**Comment by Stephan-MDD** [comment]
@rphlmr sorry for the late response,

I dont have any `vite.config.ts.timestamp-1722166454203-402425dcb8915.mjs` my code is 1 to 1 with the main branch. Event when I make a global search for the file nothing appears in the project. I delete every thing from docker so nothing should be saved/cached but I still get the same error.

I read the issue on Vite and it seems like the error is the same. Thanks for mentioning it :)

It seems like a bit much to remove all `*.timestamp...` files with pre-script like some of the solutions.
Is there anything you can recommend? :)

**Comment by ShafSpecs** [comment]
Unfortunately no. And working with Vite itself is out of scope for Remix PWA as we aim to follow along with Remix changes. Personally, I think pre-script would be your best and most direct shot, every other possible solution I can give rn would just be a hack or complicated abstractions :+1:

**Comment by Stephan-MDD** [comment]
@ShafSpecs 
I'll see what I can do from here then - thanks everyone for your help and time :)

**Comment by Bob-six** [comment]
@Stephan-MDD I'm facing the same issue, seems like running it with node fixes it.

i think the issue of bun is specified here https://github.com/oven-sh/bun/issues/15946

**Comment by Bob-six** [comment]
@Stephan-MDD i have the similar issue running remix pwa with bun. but when i run it again with nodejs it compiles without any errors


i think the issue is from bun https://github.com/oven-sh/bun/issues/15946

**Comment by Stephan-MDD** [comment]
Thanks @Bob-six I ended up using nodejs - but it would be nice to use Bun😃 I'll give it a try if the link have any solutions 😊

**Comment by phpmac** [comment]
https://github.com/oven-sh/bun/issues/18419

**Comment by phpmac** [comment]
I think this is a problem because I switched to bun and encountered the same issue.

**Comment by phpmac** [comment]
Currently forced to stop using PWA
